### PR TITLE
Logic fixes for rounds with partial echo

### LINKED ISSUE #21: Add an example of a protocol that only sends messages to a subset of nodes
This will be similar to a key resharing protocol. We have a set of "old holders" that sends messages to a set of "new holders", and these sets may intersect or coincide.

### PR DESCRIPTION
**Pull request by fjarri**
Fixes #21

Imagine the following round configuration (which is possible during KeyResharing from `synedrion`):
- node 0 sends an echo-broadcast to [1, 2, 3]
- node 1 sends an echo-broadcast to [2, 3]
- nodes 2 and 3 do not send echo-broadcasts

After we received the initial broadcasts, we want an echo round where the nodes 1, 2, 3 echo received messages to each other. That is:
- node 0 does not send or receive anything
- node 1 sends the broadcasts from [0] to 2 and 3, and expects [0, 1] from 2 and 3
- node 2 sends the broadcasts from [0, 1] to 1 and 3, and expects [0] from 1 and [0, 1] from 3
- node 3 sends the broadcasts from [0, 1] to 1 and 2, and expects [0] from 1 and [0, 1] from 2

(note that node 1 does not send its broadcast the second time; that would be pointless)

This requires adding another method to `Round` specifying the exact behavior of the node, since this information cannot be obtained from existing methods. This PR introduces `Round::echo_round_participation()` and `EchoRoundParticipation` enum. 

In most cases we can use the blanket implementation returning `EchoRoundParticipation`, which means that the node either sends and receives echo messages, or does neither. This means that we can deduce the properties of the echo round from `Round::message_destinations()` and `Round::expecting_messages_from()`. The case where the node only sends echo messages (node 0), we don't need any additional info other than this fact. For the case where the node only receives echo messages (node 3), it needs additional info specifying which nodes actually participate in the echo round.

*Edit:* another possible API here is to get rid of `EchoRoundParticipation` enum and instead have a method returning `Option<BTreeSet<Id>>`. `None` would cover both `Default` and `Send`, and we will distinguish between them by checking if `expecting_messages_from()` is empty or not. Would that work?

### CODE REVIEW

File: manul/src/protocol/round.rs [hunk 1]
```diff
@@ -322,6 +322,25 @@ pub trait PartyId: 'static + Debug + Clone + Ord + Send + Sync {}
 
 impl<T> PartyId for T where T: 'static + Debug + Clone + Ord + Send + Sync {}
 
+/// The specific way the node participates in the echo round (if any).
+#[derive(Debug, Clone)]
+pub enum EchoRoundParticipation<Id> {
+    /// The default behavior: sends broadcasts and receives echoed messages, or does neither.
+    ///
+    /// That is, this node will be a part of the echo round if [`Round::make_echo_broadcast`] generates a message.
+    Default,
```
Comment (dvdplm) [inline manul/src/protocol/round.rs:331]: Would `Full` be a good name here? It doesn't fully capture the semantics but is at least a hint in the right direction whereas "default" doesn't mean anything unless the reader knows what the default is.

**Review by dvdplm — COMMENTED** [review]
I'm struggling a bit to review this. The code seems all ok, modulo nitpicks, but I'm kind of stuck in my head on why we need this (despite the great PR description). E.g. in the `partial_echo` test, how should I think about a real world scenario there? Would node 0 be like a "dealer" of some sort, broadcasting but not participating? And what would node 4 be, given it's not participating at all?

File: clippy.toml [hunk 2]
```diff
@@ -1 +0,0 @@
-allow-unwrap-in-tests = true
```
[the remark this answers is not in the document]
Comment (fjarri) [reply clippy.toml:1]: For whatever reason, it is not.

File: manul/src/session/session.rs [hunk 3]
```diff
@@ -97,6 +97,13 @@ impl AsRef<[u8]> for SessionId {
     }
 }
 
+#[derive(Debug)]
+pub(crate) struct EchoRoundInfo<Verifier> {
+    pub(crate) message_destinations: BTreeSet<Verifier>,
+    pub(crate) expecting_messages_from: BTreeSet<Verifier>,
+    pub(crate) expected_echos: BTreeSet<Verifier>,
```
[the remark this answers is not in the document]
Comment (fjarri) [reply manul/src/session/session.rs:104]: It wouldn't be a little ambiguous I think. `expected_echos` is the set of echos you're expecting to find in a pack that's sent to you (from any node), and `expecting_echos_from` could be understood as the nodes that need to send the echo packs to you. These can be different.

File: manul/src/protocol/round.rs (hunk 1 above)
Comment (fjarri) [reply manul/src/protocol/round.rs:331]: Funny you should say that, `Full` was the original name I had here :) But I changed it to `Default` because it also covers the nodes which don't send or receive anything (node 4 in the test), where I wasn't sure `Full` was intuitive.

File: manul/src/session/session.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (dvdplm) [reply manul/src/session/session.rs:104]: Hmm. Maybe just `echoes` works then?

File: manul/src/protocol/round.rs (hunk 1 above)
Comment (dvdplm) [reply manul/src/protocol/round.rs:376]: `Full` isn't perfect, but gives a hint to the right understanding. I like it better than `Default`.

We could go with a `FullOrAbsent` but that reads very confusingly. :)

File: manul/Cargo.toml [hunk 4]
```diff
@@ -20,6 +20,7 @@ rand_core = { version = "0.6.4", default-features = false }
 tracing = { version = "0.1", default-features = false }
 displaydoc = { version = "0.2", default-features = false }
 derive-where = "1"
+smallvec = { version = "1", default-features = false, features = ["serde"] }
```
Comment (dvdplm) [inline manul/Cargo.toml:23]: There's an argument to prefer `tinyvec` to `smallvec`, given the former has a "no unsafe" policy (and the latter has had a few memory related bugs over the years).

Another tangential thought: RustCrypto use the [hybrid_array](https://crates.io/crates/hybrid-array) so we probably have it in the dependency tree. I haven't looked into it but perhaps it can be used here too?

File: manul/src/protocol/round.rs [hunk 5]
```diff
@@ -29,24 +30,18 @@ pub enum FinalizeOutcome<Id: PartyId, P: Protocol> {
     Result(P::Result),
 }
 
-// Maximum depth of group nesting in RoundIds.
-// We need this to be limited to allow the nesting to be performed in `const` context
-// (since we cannot use heap there).
-const ROUND_ID_DEPTH: usize = 8;
-
 /// A round identifier.
-#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
```
Comment (dvdplm) [inline manul/src/protocol/round.rs:73]: It's too bad SmallVec isn't `Copy`. :/

**Review by dvdplm — APPROVED** [review]

File: manul/Cargo.toml (hunk 4 above)
Comment (fjarri) [reply manul/Cargo.toml]: `hybrid_array` deals exclusively with stack arrays, I think.
